// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETuuBqV8DNLy8ucq-iZwpLgAuwfOLZ9Y',
    appId: '1:829087142636:web:06c3d97df17607190c8bc9',
    messagingSenderId: '829087142636',
    projectId: 'diafootcare-21be7',
    authDomain: 'diafootcare-21be7.firebaseapp.com',
    storageBucket: 'diafootcare-21be7.firebasestorage.app',
    measurementId: 'G-5CTS3EY7V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5AKS0QPmVXZMb2xgFCBluzbsfYW-ecQ',
    appId: '1:829087142636:android:6e1a20374f9e1b8a0c8bc9',
    messagingSenderId: '829087142636',
    projectId: 'diafootcare-21be7',
    storageBucket: 'diafootcare-21be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT2_FfZFfJUnywSmtdzzeyOr_OVAIAVbQ',
    appId: '1:829087142636:ios:563af6bfb0b48ca90c8bc9',
    messagingSenderId: '829087142636',
    projectId: 'diafootcare-21be7',
    storageBucket: 'diafootcare-21be7.firebasestorage.app',
    iosBundleId: 'com.example.diafootcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT2_FfZFfJUnywSmtdzzeyOr_OVAIAVbQ',
    appId: '1:829087142636:ios:563af6bfb0b48ca90c8bc9',
    messagingSenderId: '829087142636',
    projectId: 'diafootcare-21be7',
    storageBucket: 'diafootcare-21be7.firebasestorage.app',
    iosBundleId: 'com.example.diafootcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDETuuBqV8DNLy8ucq-iZwpLgAuwfOLZ9Y',
    appId: '1:829087142636:web:43641c6102d942400c8bc9',
    messagingSenderId: '829087142636',
    projectId: 'diafootcare-21be7',
    authDomain: 'diafootcare-21be7.firebaseapp.com',
    storageBucket: 'diafootcare-21be7.firebasestorage.app',
    measurementId: 'G-7Z6X055VGR',
  );

}